/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hlyemphtqtjwydbpqrdr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhseWVtcGh0cXRqd3lkYnBxcmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NzIxNzQsImV4cCI6MjA3NzA0ODE3NH0.vzmJIDClIaO0kvq-sgkZ4fMKZUj-gcG8vC8MPjKuBnM"